server:
  port: 9001
  connectionTimeout: 30s

spring:
  application:
    name: echo

  servlet:
    multipart:
      max-file-size: 50MB # 配置单个文件大小上限
      max-request-size: 50MB # 配置单次请求大小上限

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.7:13306/bop?serverTimezone=GMT
    username: al
    password: 169617
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  devtools:
    restart:
      enabled: true

info:
  app:
    name: 邮件服务
    version: 0.0.1

logging:
  level:
    com.beyondsoft.bop.mapper: debug

